apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ include "litellm.fullname" . }}-masterkey
spec:
  path: {{ required "vault.masterkey.path is required" .Values.vault.masterkey.path | quote }}
  type: Opaque
