apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ include "litellm.fullname" . }}-dbcredentials
spec:
  path: {{ required "vault.dbcredentials.path is required" .Values.vault.dbcredentials.path | quote }}
  type: Opaque
  keys:
    {{- range .Values.vault.dbcredentials.envs }}
    - {{ .key }}
    {{- end }}
