services:
  litellm:
    image: ghcr.io/berriai/litellm-database:main-stable
    volumes:
      - ./config.yaml:/app/config.yaml
    env_file:
      - .env
    command: ["--config", "/app/config.yaml", "--detailed_debug"]
    container_name: litellm_app
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health/liveliness"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - litellm-net

  db:
    image: postgres:18-alpine
    container_name: litellm_db
    env_file:
      - .env
    volumes:
      - litellm_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - litellm-net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: litellm_pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "127.0.0.1:5050:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - litellm-net

volumes:
  litellm_pg_data:
  pgadmin_data:

networks:
  litellm-net:
    name: litellm-net
    external: true
